name: Code Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  call_reusable_workflow:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-code-coverage.yml@main
    with:
      before_install_target_dependencies: './scripts/ci_install_dependencies.sh'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
